---
- name: Install common dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

# ---------------- Docker Setup ----------------

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

# ---------------- Kubernetes Setup (Safe for Ubuntu 22.04) ----------------

- name: Remove any old Kubernetes key or repo (if exists)
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/kubernetes.list
    - /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes GPG key (Google recommended location)
  shell: |
    curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  args:
    creates: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes apt repository using blockinfile (signed-by)
  blockinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    create: yes
    block: |
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main

- name: Update APT cache after adding Kubernetes repo
  apt:
    update_cache: yes

- name: Install kubelet, kubeadm, and kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages to prevent automatic upgrades
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    force: yes
    autoremove: no
    upgrade: no
    dpkg_options: "hold"
