---
- name: Install common dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

# ---------------- Docker Setup ----------------

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

# ---------------- Kubernetes Setup (Modern Mirror) ----------------

- name: Clean up old Kubernetes repo and keys if present
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/kubernetes.list
    - /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Create keyrings directory if missing
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes GPG key for pkgs.k8s.io
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | \
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Add Kubernetes APT repo (v1.29+ modern)
  blockinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    create: yes
    block: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /

- name: Update apt cache after adding Kubernetes repo
  apt:
    update_cache: yes

- name: Install Kubernetes tools
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes versions to prevent automatic upgrades
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    force: yes
    autoremove: no
    upgrade: no
    dpkg_options: "hold"
