apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: cluster.k8s.local
spec:
  cloudProvider: aws
  kubernetesVersion: "1.29.0"
  networking:
    kubenet: {}
  zones:
    - us-east-2a
    - us-east-2b
  controlPlaneZones:
    - us-east-2a
  etcdClusters:
    - name: main
      etcdMembers:
        - name: a
          instanceGroup: master-us-east-2a
  topology:
    masters: public
    nodes: public
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: master-us-east-2a
spec:
  role: Master
  instanceRole: Master
  machineType: t3.medium
  minSize: 1
  maxSize: 1
  subnets:
    - us-east-2a
  sshKeyName: linux  # 👈 Your existing EC2 key pair
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes
spec:
  role: Node
  machineType: t3.medium
  minSize: 2
  maxSize: 2
  subnets:
    - us-east-2a
    - us-east-2b
  sshKeyName: linux  # 👈 Your existing EC2 key pair
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: workstation
spec:
  role: Node
  machineType: t3.micro
  minSize: 1
  maxSize: 1
  subnets:
    - us-east-2a
  sshKeyName: linux  # 👈 Your existing EC2 key pair
