- name: Install AWS CLI, Kops, Kubectl
  hosts: localhost
  become: yes
  tasks:

    - name: Install unzip and curl
      apt:
        name:
          - unzip
          - curl
        state: present

    - name: Install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mv kubectl /usr/local/bin/
      args:
        creates: /usr/local/bin/kubectl

    - name: Install kops
      shell: |
        curl -Lo kops https://github.com/kubernetes/kops/releases/latest/download/kops-linux-amd64
        chmod +x kops
        mv kops /usr/local/bin/
      args:
        creates: /usr/local/bin/kops
